"""add primary key in apple wallet settings

Revision ID: 0053a68ec9ec
Revises: merge_heads_001
Create Date: 2025-10-31 22:26:48.904180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0053a68ec9ec'
down_revision = 'merge_heads_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'apple_wallet_card_settings', ['cashbox_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apple_wallet_card_settings', type_='unique')
    # ### end Alembic commands ###
