"""tg bot bills

Revision ID: 03681c4be0e8
Revises: 1c6b9cf07506
Create Date: 2025-02-18 19:21:56.272722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03681c4be0e8'
down_revision = '1c6b9cf07506'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_bot_bills',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('s3_url', sa.String(), nullable=False),
        sa.Column('plain_text', sa.String(), nullable=False),
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column('tochka_bank_account_id', sa.Integer(), nullable=True),
        sa.Column('payment_amount', sa.Float(), nullable=True),
        sa.Column('counterparty_account_number', sa.String(), nullable=True),
        sa.Column('payment_purpose', sa.String(), nullable=True),
        sa.Column('counterparty_bank_bic', sa.String(), nullable=True),
        sa.Column('counterparty_name', sa.String(), nullable=True),
        sa.Column('corr_account', sa.String(), nullable=True),
        sa.Column('status', sa.Enum('NEW', 'WAITING_FOR_APPROVAL', 'APPROVED', 'CANCELED', 'REJECTED', 'REQUESTED', 'PAID', 'ERROR', name='tgbillstatus'), nullable=False),
        sa.Column('request_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_tg_bot_bills'),  # Name the primary key
        sa.ForeignKeyConstraint(['created_by'], ['tg_accounts.id'], name='fk_tg_bot_bills_created_by'), # Name the foreign key
        sa.ForeignKeyConstraint(['tochka_bank_account_id'], ['tochka_bank_accounts.id'], name='fk_tg_bot_bills_tochka_bank_account_id') # Name the foreign key
    )
    
    op.create_table('tg_bot_bill_approvers',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('approver_id', sa.Integer(), nullable=False),
        sa.Column('bill_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('NEW', 'APPROVED', 'CANCELED', name='tgbillapprovestatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_tg_bot_bill_approvers'), # Name the primary key
        sa.ForeignKeyConstraint(['approver_id'], ['tg_accounts.id'], name='fk_tg_bot_bill_approvers_approver_id'), # Name the foreign key
        sa.ForeignKeyConstraint(['bill_id'], ['tg_bot_bills.id'], name='fk_tg_bot_bill_approvers_bill_id') # Name the foreign key
        
    )
    

def downgrade() -> None:
    op.drop_constraint('fk_tg_bot_bill_approvers_bill_id', 'tg_bot_bill_approvers', type_='foreignkey')
    op.drop_constraint('fk_tg_bot_bill_approvers_approver_id', 'tg_bot_bill_approvers', type_='foreignkey')
    op.drop_constraint('pk_tg_bot_bill_approvers', 'tg_bot_bill_approvers', type_='primary')
    op.drop_table('tg_bot_bill_approvers')

    op.drop_constraint('fk_tg_bot_bills_tochka_bank_account_id', 'tg_bot_bills', type_='foreignkey')
    op.drop_constraint('fk_tg_bot_bills_created_by', 'tg_bot_bills', type_='foreignkey')
    op.drop_constraint('pk_tg_bot_bills', 'tg_bot_bills', type_='primary')
    op.drop_table('tg_bot_bills')

    op.execute("DROP TYPE IF EXISTS tgbillapprovestatus")
    op.execute("DROP TYPE IF EXISTS tgbillstatus")
