"""add/client_segment_history

Revision ID: 0ba58423583e
Revises: b434531c9ee3
Create Date: 2025-06-02 21:45:46.054135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ba58423583e'
down_revision = 'b434531c9ee3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_segment_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('contragent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('added', 'deleted', name='segmentstatushistory'), nullable=False),
    sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_segment_history_id'), 'client_segment_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_segment_history_id'), table_name='client_segment_history')
    op.drop_table('client_segment_history')
    op.execute("DROP TYPE segmentstatushistory")
    # ### end Alembic commands ###
