"""add_dc_to_articles

Revision ID: 1366a50d9d76
Revises: 373c2315dcef
Create Date: 2025-03-29 15:12:45.240336

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1366a50d9d76'
down_revision = 'c900ea9bbaf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    debitcredit_enum = postgresql.ENUM('debit', 'credit', name='debitcredittype',
                                       create_type=False)
    debitcredit_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('articles', sa.Column('dc', sa.Enum('debit', 'credit', name='debitcredittype'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('articles', 'dc')
    op.execute('DROP TYPE IF EXISTS debitcredittype')
    # ### end Alembic commands ###
