"""add_amo_webhooks

Revision ID: 170143dc7ab4
Revises: 6dcd82b23035
Create Date: 2025-08-13 23:55:26.690708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170143dc7ab4'
down_revision = '6dcd82b23035'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_webhooks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('amo_install_group_id', sa.Integer(), nullable=True),
        sa.Column('amo_id', sa.BigInteger(), nullable=True),
        sa.Column('created_by', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=True),
        sa.Column('sort', sa.Integer(), nullable=True),
        sa.Column('disabled', sa.Boolean(), nullable=True),
        sa.Column('destination', sa.String(), nullable=True),
        sa.Column('settings', sa.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
        sa.ForeignKeyConstraint(['amo_install_group_id'], ['amo_install_groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('amo_install_group_id', 'amo_id',
                            name='uq_amo_webhooks_amo_install_group_id_amo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amo_webhooks')
    # ### end Alembic commands ###
