"""column_is_system_in_price_types

Revision ID: 1853c50d00b7
Revises: a5f90f1d17da
Create Date: 2025-08-09 15:06:49.136476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1853c50d00b7'
down_revision = 'a5f90f1d17da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_types', sa.Column('is_system', sa.Boolean(), nullable=True))
    op.execute("""
        INSERT INTO price_types (name, owner, cashbox, is_deleted, is_system) 
        SELECT 'chatting', relation_tg_cashboxes.id, relation_tg_cashboxes.cashbox_id, FALSE, TRUE
        FROM relation_tg_cashboxes
        WHERE NOT EXISTS(
          SELECT 1
          FROM price_types p 
          WHERE p.owner = relation_tg_cashboxes.id  AND p.is_system = TRUE
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM price_types
        WHERE is_system = TRUE;
    """)
    op.drop_column('price_types', 'is_system')
    # ### end Alembic commands ###
