"""add seo params

Revision ID: 1c68f42fc047
Revises: 6d6ce46bbd44
Create Date: 2025-08-24 11:17:28.611819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c68f42fc047'
down_revision = '6d6ce46bbd44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomenclature', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('nomenclature', sa.Column('seo_description', sa.String(), nullable=True))
    op.add_column('nomenclature', sa.Column('seo_keywords', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nomenclature', 'seo_keywords')
    op.drop_column('nomenclature', 'seo_description')
    op.drop_column('nomenclature', 'seo_title')
