"""yookassa_payments

Revision ID: 1c6b9cf07506
Revises: 7fa9039fda7c
Create Date: 2025-02-14 11:51:50.907493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6b9cf07506'
down_revision = '7fa9039fda7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yookassa_payments', sa.Column('payment_id', sa.String(), nullable=True))
    op.add_column('yookassa_payments', sa.Column('confirmation_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yookassa_payments', 'confirmation_url')
    op.drop_column('yookassa_payments', 'payment_id')
    # ### end Alembic commands ###
