"""empty message

Revision ID: 282fa3cb3e98
Revises: e090f4caa808
Create Date: 2024-12-16 11:42:24.332257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282fa3cb3e98'
down_revision = 'e090f4caa808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'amo_bots', ['install_group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'amo_bots', type_='unique')
    # ### end Alembic commands ###
