"""add_lead_contacts

Revision ID: 316365d6d617
Revises: f82fc5198d96
Create Date: 2025-06-26 12:21:36.273479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316365d6d617'
down_revision = 'f82fc5198d96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_lead_contacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('amo_install_group_id', sa.Integer(), nullable=True),
        sa.Column('lead_id', sa.BigInteger(), nullable=True),
        sa.Column('contact_id', sa.BigInteger(), nullable=True),
        sa.Column('is_main', sa.Boolean(), server_default='true', nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['amo_install_group_id'], ['amo_install_groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('amo_install_group_id', 'lead_id', 'contact_id', name='uq_amo_lead_contacts_group_lead_contact')
    )
    op.create_index(op.f('ix_amo_lead_contacts_id'), 'amo_lead_contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amo_lead_contacts_id'), table_name='amo_lead_contacts')
    op.drop_table('amo_lead_contacts')
    # ### end Alembic commands ###
