"""update apple wallet

Revision ID: 33de7c3df2b7
Revises: b93707ca0d3d
Create Date: 2025-10-18 10:54:39.312197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33de7c3df2b7'
down_revision = 'b93707ca0d3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('apple_push_tokens', sa.Column('card_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'apple_push_tokens', 'loyality_cards', ['card_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apple_push_tokens', type_='foreignkey')
    op.drop_column('apple_push_tokens', 'card_id')
