"""add shifts

Revision ID: 3df9a9052a94
Revises: 61daf2cd92aa
Create Date: 2025-08-27 14:11:31.710783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df9a9052a94'
down_revision = '61daf2cd92aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=False),
    sa.Column('shift_start', sa.DateTime(), nullable=False),
    sa.Column('shift_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('on_shift', 'off_shift', 'on_break', name='shiftstatus'), server_default='off_shift', nullable=False),
    sa.Column('break_start', sa.DateTime(), nullable=True),
    sa.Column('break_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['relation_tg_cashboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_shifts_id'), 'employee_shifts', ['id'], unique=False)
    op.add_column('relation_tg_cashboxes', sa.Column('shift_work_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relation_tg_cashboxes', 'shift_work_enabled')
    op.drop_index(op.f('ix_employee_shifts_id'), table_name='employee_shifts')
    op.drop_table('employee_shifts')
    # ### end Alembic commands ###
