"""add_tables_for_tinkoff

Revision ID: 43e4a2d80a61
Revises: e55ec8843476
Create Date: 2024-10-19 14:13:45.853922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e4a2d80a61'
down_revision = 'e55ec8843476'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbank_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_key', sa.Text(), nullable=True),
    sa.Column('invite_token', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbank_accounts_id'), 'tbank_accounts', ['id'], unique=False)
    op.create_table('tbank_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invite_token', sa.Text(), nullable=True),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('tbank_payment_id', sa.Text(), nullable=True),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbank_orders_id'), 'tbank_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbank_orders_id'), table_name='tbank_orders')
    op.drop_table('tbank_orders')
    op.drop_index(op.f('ix_tbank_accounts_id'), table_name='tbank_accounts')
    op.drop_table('tbank_accounts')
    # ### end Alembic commands ###
