"""Add Amo Install Widget Installer

Revision ID: 51a676700853
Revises: 89a772027e2e
Create Date: 2024-10-05 21:54:26.971440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a676700853'
down_revision = '89a772027e2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_install_widget_installer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amo_account_id', sa.BigInteger(), nullable=True),
    sa.Column('installed_by_role', sa.Enum('Partner', 'Client', name='installedbyrole'), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('partner_name', sa.String(), nullable=True),
    sa.Column('client_cashbox', sa.Integer(), nullable=True),
    sa.Column('partner_cashbox', sa.Integer(), nullable=True),
    sa.Column('client_number_phone', sa.String(), nullable=True),
    sa.Column('partner_number_phone', sa.String(), nullable=True),
    sa.Column('client_inn', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amo_account_id')
    )
    op.create_index(op.f('ix_amo_install_widget_installer_id'), 'amo_install_widget_installer', ['id'], unique=False)
    op.create_unique_constraint(None, 'amo_users', ['amo_install_group_id', 'ext_id'])
    op.create_unique_constraint(None, 'booking_events_photo', ['booking_event_id', 'photo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_events_photo', type_='unique')
    op.drop_constraint(None, 'amo_users', type_='unique')
    op.drop_index(op.f('ix_amo_install_widget_installer_id'), table_name='amo_install_widget_installer')
    op.drop_table('amo_install_widget_installer')
    # ### end Alembic commands ###
