"""fix/segment_model

Revision ID: 52846ed362ac
Revises: 0ba58423583e
Create Date: 2025-06-06 19:06:18.977903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52846ed362ac'
down_revision = '0ba58423583e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    segment_status_enum = postgresql.ENUM(
        'created', 'in_process', 'calculated', name='segmentstatus'
    )
    segment_status_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('previous_update_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('segments', sa.Column('status', segment_status_enum, server_default='created', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'status')
    op.drop_column('segments', 'previous_update_at')
    op.execute("DROP TYPE segmentstatus")
    # ### end Alembic commands ###
