"""add apple_wallet_advertisement

Revision ID: 58249a41dca1
Revises: 867f3c2814e5
Create Date: 2025-10-23 09:40:44.436701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58249a41dca1'
down_revision = '867f3c2814e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apple_push_tokens', 'have_updates')
    op.add_column('loyality_cards', sa.Column('apple_wallet_advertisement', sa.String(), server_default='TableCRM', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loyality_cards', 'apple_wallet_advertisement')
    op.add_column('apple_push_tokens', sa.Column('have_updates', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
