"""fix/segment_model

Revision ID: 5bfab8513113
Revises: 52846ed362ac
Create Date: 2025-06-09 22:03:54.865360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bfab8513113'
down_revision = '52846ed362ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('cashbox_id', sa.Integer(), nullable=True))
    op.drop_index('ix_segments_uuid', table_name='segments')
    op.drop_constraint('segments_created_by_fkey', 'segments', type_='foreignkey')
    op.create_foreign_key('segments_cashbox_id_fkey', 'segments', 'cashboxes', ['cashbox_id'], ['id'])
    op.drop_column('segments', 'uuid')
    op.drop_column('segments', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('segments', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('segments_cashbox_id_fkey', 'segments', type_='foreignkey')
    op.create_foreign_key('segments_created_by_fkey', 'segments', 'relation_tg_cashboxes', ['created_by'], ['id'])
    op.create_index('ix_segments_uuid', 'segments', ['uuid'], unique=False)
    op.drop_column('segments', 'cashbox_id')
    # ### end Alembic commands ###
