"""add payment_past_edit_days and timezone in cashbox_user

Revision ID: 5c9cbc4aa7c4
Revises: b9d5fafd393d
Create Date: 2025-08-08 17:28:20.176235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9cbc4aa7c4'
down_revision = 'b9d5fafd393d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation_tg_cashboxes', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('relation_tg_cashboxes', sa.Column('payment_past_edit_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relation_tg_cashboxes', 'payment_past_edit_days')
    op.drop_column('relation_tg_cashboxes', 'timezone')
    # ### end Alembic commands ###
