"""entity-hash-table-partitioning

Revision ID: 61daf2cd92aa
Revises: 1853c50d00b7
Create Date: 2025-08-20 19:08:31.216599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61daf2cd92aa'
down_revision = '1853c50d00b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_hash',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('warehouses_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouses_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomenclature_hash',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nomenclature', sa.Column('chatting_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nomenclature', 'chatting_percent')
    op.drop_table('nomenclature_hash')
    op.drop_table('warehouse_hash')
    # ### end Alembic commands ###
