"""yookassa_table_payments_add_field_payment_capture

Revision ID: 620ecf0db322
Revises: 72dfb72bf6e4
Create Date: 2025-03-12 14:39:25.441154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620ecf0db322'
down_revision = '4979093a5519'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yookassa_payments', sa.Column('payment_capture', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yookassa_payments', 'payment_capture')
    # ### end Alembic commands ###
