"""add/selection_fiels_to_segment

Revision ID: 6c91495eeb73
Revises: 7013fb4d03cd
Create Date: 2025-06-26 20:50:04.653602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c91495eeb73'
down_revision = '7013fb4d03cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('selection_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'selection_field')
    # ### end Alembic commands ###
