"""empty message

Revision ID: 6eacf82668e4
Revises: 743a97ce9f01
Create Date: 2024-12-23 09:35:18.372722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eacf82668e4'
down_revision = '743a97ce9f01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_triggers_events', sa.Column('loyality_transactions_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'table_triggers_events', 'loyality_transactions', ['loyality_transactions_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_triggers_events', type_='foreignkey')
    op.drop_column('table_triggers_events', 'loyality_transactions_id')
    # ### end Alembic commands ###
