"""add/user_and_nomenclature_tags

Revision ID: 7013fb4d03cd
Revises: dfa79fb8b227
Create Date: 2025-06-21 14:22:27.713796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7013fb4d03cd'
down_revision = 'dfa79fb8b227'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomenclature', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('relation_tg_cashboxes', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relation_tg_cashboxes', 'tags')
    op.drop_column('nomenclature', 'tags')
    # ### end Alembic commands ###
