"""add/feeds_and_feed_tags

Revision ID: 722d96cec7fb
Revises: 3df9a9052a94
Create Date: 2025-09-13 22:05:23.815721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722d96cec7fb'
down_revision = 'b966f1edb05f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url_token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('root_tag', sa.String(), nullable=False),
    sa.Column('item_tag', sa.String(), nullable=False),
    sa.Column('field_tags', sa.JSON(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('cashbox_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeds_cashbox_id'), 'feeds', ['cashbox_id'], unique=False)
    op.create_index(op.f('ix_feeds_id'), 'feeds', ['id'], unique=False)
    op.create_index(op.f('ix_feeds_url_token'), 'feeds', ['url_token'], unique=True)
    op.create_table('feeds_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'feed_id', name='unique_tag_id_feed_id')
    )
    op.create_index(op.f('ix_feeds_tags_id'), 'feeds_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feeds_tags_id'), table_name='feeds_tags')
    op.drop_table('feeds_tags')
    op.drop_index(op.f('ix_feeds_url_token'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_id'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_cashbox_id'), table_name='feeds')
    op.drop_table('feeds')
    # ### end Alembic commands ###
