"""empty message

Revision ID: 743a97ce9f01
Revises: aff3ea629e6a
Create Date: 2024-12-23 08:55:32.329672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743a97ce9f01'
down_revision = 'aff3ea629e6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_triggers_events', sa.Column('install_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'table_triggers_events', 'amo_install_groups', ['install_group_id'], ['id'])
    op.drop_column('table_triggers_events', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_triggers_events', sa.Column('client', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'table_triggers_events', type_='foreignkey')
    op.drop_column('table_triggers_events', 'install_group_id')
    # ### end Alembic commands ###
