"""Add External Id To Manufacturers

Revision ID: 74b7d63c1eb4
Revises: 373c2315dcef
Create Date: 2025-03-30 02:28:14.554357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b7d63c1eb4'
down_revision = '373c2315dcef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('external_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturers', 'external_id')
    # ### end Alembic commands ###
