"""add/segment_versions

Revision ID: 7e434c43ca49
Revises: f7df2c79bff0
Create Date: 2025-07-26 14:00:49.572061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e434c43ca49'
down_revision = 'f7df2c79bff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'version', name='uq_segment_version')
    )
    op.create_index(op.f('ix_segment_versions_id'), 'segment_versions', ['id'], unique=False)
    op.create_table('segment_version_objects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('object_type', sa.Enum('docs_sales', 'contragents', name='segment_object_type'), nullable=False),
    sa.Column('change_type', sa.Enum('added', 'removed', 'existing', name='segment_change_type'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.ForeignKeyConstraint(['version'], ['segment_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'version', 'object_id', 'object_type', 'change_type', name='uq_svo_unique_object_per_version')
    )
    op.create_index(op.f('ix_segment_version_objects_change_type'), 'segment_version_objects', ['change_type'], unique=False)
    op.create_index(op.f('ix_segment_version_objects_id'), 'segment_version_objects', ['id'], unique=False)
    op.create_index(op.f('ix_segment_version_objects_object_id'), 'segment_version_objects', ['object_id'], unique=False)
    op.create_index(op.f('ix_segment_version_objects_object_type'), 'segment_version_objects', ['object_type'], unique=False)
    op.create_index('ix_svo_object_type', 'segment_version_objects', ['object_id', 'object_type'], unique=False)
    op.create_index('ix_svo_segment_version', 'segment_version_objects', ['segment_id', 'version'], unique=False)
    op.drop_index('ix_client_segment_history_id', table_name='client_segment_history')
    op.drop_table('client_segment_history')
    op.drop_index('ix_client_segments_id', table_name='client_segments')
    op.drop_table('client_segments')
    op.add_column('segments', sa.Column('current_version', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_segments_cashbox_id'), 'segments', ['cashbox_id'], unique=False)
    op.create_index(op.f('ix_segments_current_version'), 'segments', ['current_version'], unique=False)
    op.drop_column('segments', 'last_added_ids')
    op.drop_column('segments', 'selection_field')
    op.drop_column('segments', 'current_ids')
    op.drop_column('segments', 'last_removed_ids')
    op.execute('DROP TYPE IF EXISTS segmentstatushistory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('last_removed_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('segments', sa.Column('current_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('segments', sa.Column('selection_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('segments', sa.Column('last_added_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_segments_current_version'), table_name='segments')
    op.drop_index(op.f('ix_segments_cashbox_id'), table_name='segments')
    op.drop_column('segments', 'current_version')
    op.create_table('client_segments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('contragent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], name='client_segments_contragent_id_fkey'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name='client_segments_segment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='client_segments_pkey')
    )
    op.create_index('ix_client_segments_id', 'client_segments', ['id'], unique=False)
    op.create_table('client_segment_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('contragent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('added', 'deleted', name='segmentstatushistory'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], name='client_segment_history_contragent_id_fkey'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name='client_segment_history_segment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='client_segment_history_pkey')
    )
    op.create_index('ix_client_segment_history_id', 'client_segment_history', ['id'], unique=False)
    op.drop_index('ix_svo_segment_version', table_name='segment_version_objects')
    op.drop_index('ix_svo_object_type', table_name='segment_version_objects')
    op.drop_index(op.f('ix_segment_version_objects_object_type'), table_name='segment_version_objects')
    op.drop_index(op.f('ix_segment_version_objects_object_id'), table_name='segment_version_objects')
    op.drop_index(op.f('ix_segment_version_objects_id'), table_name='segment_version_objects')
    op.drop_index(op.f('ix_segment_version_objects_change_type'), table_name='segment_version_objects')
    op.drop_table('segment_version_objects')
    op.drop_index(op.f('ix_segment_versions_id'), table_name='segment_versions')
    op.drop_table('segment_versions')
    op.execute('DROP TYPE IF EXISTS segment_object_type')
    op.execute('DROP TYPE IF EXISTS segment_change_type')
    # ### end Alembic commands ###
