"""fix/segment_obj

Revision ID: 7f34773f5e73
Revises: 7e434c43ca49
Create Date: 2025-08-01 22:00:39.766617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f34773f5e73'
down_revision = '7e434c43ca49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_segment_version_objects_change_type', table_name='segment_version_objects')
    op.drop_index('ix_segment_version_objects_id', table_name='segment_version_objects')
    op.drop_index('ix_segment_version_objects_object_id', table_name='segment_version_objects')
    op.drop_index('ix_segment_version_objects_object_type', table_name='segment_version_objects')
    op.drop_index('ix_svo_object_type', table_name='segment_version_objects')
    op.drop_index('ix_svo_segment_version', table_name='segment_version_objects')
    op.drop_table('segment_version_objects')
    op.execute('DROP TYPE IF EXISTS segment_object_type')
    segment_object_type_enum = sa.Enum(
    'docs_sales',
    'contragents',
    name='segment_object_type'
    )
    segment_object_type_enum.create(op.get_bind())   

    op.create_table(
    'segment_objects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('object_type', segment_object_type_enum, nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'object_id', 'object_type', 'valid_from', 'valid_to', name='uq_svo_unique_object_per_move')
    )
    op.create_index(op.f('ix_segment_objects_id'), 'segment_objects', ['id'], unique=False)
    op.create_index(op.f('ix_segment_objects_object_id'), 'segment_objects', ['object_id'], unique=False)
    op.create_index(op.f('ix_segment_objects_object_type'), 'segment_objects', ['object_type'], unique=False)
    op.create_index('ix_svo_segment_valid_from', 'segment_objects', ['segment_id', 'valid_from'], unique=False)
    op.create_index('ix_svo_segment_valid_to', 'segment_objects', ['segment_id', 'valid_to'], unique=False)
    op.drop_index('ix_segment_versions_id', table_name='segment_versions')
    op.drop_table('segment_versions')

    op.drop_index('ix_segments_current_version', table_name='segments')
    op.drop_column('segments', 'current_version')
    op.execute('DROP TYPE IF EXISTS segment_change_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('current_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_segments_current_version', 'segments', ['current_version'], unique=False)
    op.drop_index('ix_svo_segment_valid_to', table_name='segment_objects')
    op.drop_index('ix_svo_segment_valid_from', table_name='segment_objects')
    op.drop_index(op.f('ix_segment_objects_object_type'),
                  table_name='segment_objects')
    op.drop_index(op.f('ix_segment_objects_object_id'),
                  table_name='segment_objects')
    op.drop_index(op.f('ix_segment_objects_id'), table_name='segment_objects')
    op.drop_table('segment_objects')
    op.execute('DROP TYPE IF EXISTS segment_object_type')
    op.create_table('segment_versions',
                    sa.Column('id', sa.BIGINT(), autoincrement=True,
                              nullable=False),
                    sa.Column('segment_id', sa.INTEGER(), autoincrement=False,
                              nullable=False),
                    sa.Column('version', sa.BIGINT(), autoincrement=False,
                              nullable=False),
                    sa.Column('created_at',
                              postgresql.TIMESTAMP(timezone=True),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'],
                                            name='segment_versions_segment_id_fkey'),
                    sa.PrimaryKeyConstraint('id',
                                            name='segment_versions_pkey'),
                    sa.UniqueConstraint('segment_id', 'version',
                                        name='uq_segment_version')
                    )
    op.create_index('ix_segment_versions_id', 'segment_versions', ['id'],
                    unique=False)
    op.create_table('segment_version_objects',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('object_type', postgresql.ENUM('docs_sales', 'contragents', name='segment_object_type'), autoincrement=False, nullable=False),
    sa.Column('change_type', postgresql.ENUM('added', 'removed', 'existing', name='segment_change_type'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name='segment_version_objects_segment_id_fkey'),
    sa.ForeignKeyConstraint(['version'], ['segment_versions.id'], name='segment_version_objects_version_fkey'),
    sa.PrimaryKeyConstraint('id', name='segment_version_objects_pkey'),
    sa.UniqueConstraint('segment_id', 'version', 'object_id', 'object_type', 'change_type', name='uq_svo_unique_object_per_version')
    )
    op.create_index('ix_svo_segment_version', 'segment_version_objects', ['segment_id', 'version'], unique=False)
    op.create_index('ix_svo_object_type', 'segment_version_objects', ['object_id', 'object_type'], unique=False)
    op.create_index('ix_segment_version_objects_object_type', 'segment_version_objects', ['object_type'], unique=False)
    op.create_index('ix_segment_version_objects_object_id', 'segment_version_objects', ['object_id'], unique=False)
    op.create_index('ix_segment_version_objects_id', 'segment_version_objects', ['id'], unique=False)
    op.create_index('ix_segment_version_objects_change_type', 'segment_version_objects', ['change_type'], unique=False)
    # ### end Alembic commands ###
