"""empty message

Revision ID: 7f4466d297af
Revises: 97e4fd750ed6
Create Date: 2024-11-29 14:38:34.943680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4466d297af'
down_revision = '97e4fd750ed6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
