"""yookassa table

Revision ID: 7fa9039fda7c
Revises: a2eed5d94a9e
Create Date: 2025-02-10 12:52:33.768439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa9039fda7c'
down_revision = 'a2eed5d94a9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yookassa_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amount_value', sa.Float(), nullable=True),
    sa.Column('amount_currency', sa.String(), nullable=True),
    sa.Column('income_amount_value', sa.Float(), nullable=True),
    sa.Column('income_amount_currency', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yookassa_payments_id'), 'yookassa_payments', ['id'], unique=False)
    op.add_column('yookassa_install', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'yookassa_install', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yookassa_install', type_='foreignkey')
    op.drop_column('yookassa_install', 'warehouse_id')
    op.drop_index(op.f('ix_yookassa_payments_id'), table_name='yookassa_payments')
    op.drop_table('yookassa_payments')
    # ### end Alembic commands ###
