"""add apple_wallet_card_settings

Revision ID: 867f3c2814e5
Revises: bd1abe3b8137
Create Date: 2025-10-20 07:19:01.782271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867f3c2814e5'
down_revision = 'bd1abe3b8137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apple_wallet_card_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apple_wallet_card_settings')
    # ### end Alembic commands ###
