"""add shifts events

Revision ID: 88961eb30f00
Revises: 30ddca6ff7e1
Create Date: 2025-10-09 08:29:31.660495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88961eb30f00'
down_revision = '30ddca6ff7e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_shifts_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=False),
    sa.Column('shift_status', sa.String(), nullable=False),
    sa.Column('event_start', sa.DateTime(), nullable=False),
    sa.Column('event_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.ForeignKeyConstraint(['relation_id'], ['relation_tg_cashboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_shifts_events_id'), 'employee_shifts_events', ['id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_shifts_events_id'), table_name='employee_shifts_events')
    op.drop_table('employee_shifts_events')
    # ### end Alembic commands ###
