"""Add delivery_price column

Revision ID: 3df9a9052a94
Revises: 1c68f42fc047
Create Date: 2025-08-28 15:36:34.341204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e456631deb1'
down_revision = '1c68f42fc047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs_sales_delivery_info', sa.Column('delivery_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docs_sales_delivery_info', 'delivery_price')
    # ### end Alembic commands ###
