"""empty message

Revision ID: 97e4fd750ed6
Revises: d901b6589a30
Create Date: 2024-11-29 14:13:05.650092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e4fd750ed6'
down_revision = 'd901b6589a30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_triggers', sa.Column('time_variant', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_triggers', 'time_variant')
    # ### end Alembic commands ###
