"""Add pictures to category

Revision ID: 99a5e266349c
Revises: 620ecf0db322
Create Date: 2025-03-17 22:02:52.233408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a5e266349c'
down_revision = '620ecf0db322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('photo_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'photo_id')
    # ### end Alembic commands ###
