"""yookassa_payments_crm_id_add

Revision ID: 9cbed7e801c5
Revises: 1c6b9cf07506
Create Date: 2025-02-19 09:17:29.647264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbed7e801c5'
down_revision = '03681c4be0e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yookassa_payments', sa.Column('payment_crm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'yookassa_payments', 'payments', ['payment_crm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yookassa_payments', type_='foreignkey')
    op.drop_column('yookassa_payments', 'payment_crm_id')
    # ### end Alembic commands ###
