"""fix relationships

Revision ID: a0bba82afb52
Revises: a2bb93ae9762
Create Date: 2025-06-03 17:52:48.884101

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a0bba82afb52'
down_revision = 'a2bb93ae9762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_permissions', 'payboxes', ['paybox_id'], ['id'])
    op.create_foreign_key(None, 'user_permissions', 'cashboxes', ['cashbox_id'], ['id'])
    op.create_foreign_key(None, 'user_permissions', 'relation_tg_cashboxes', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_permissions_paybox_id_fkey', 'user_permissions', type_='foreignkey')
    op.drop_constraint('user_permissions_cashbox_id_fkey', 'user_permissions', type_='foreignkey')
    op.drop_constraint('user_permissions_user_id_fkey', 'user_permissions', type_='foreignkey')
    # ### end Alembic commands ###
