"""add mp carts

Revision ID: a17a46ece83d
Revises: af297d88e7fa
Create Date: 2025-11-16 20:10:30.139592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17a46ece83d'
down_revision = 'af297d88e7fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_contragent_cart',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contragent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contragent_id')
    )
    op.create_index(op.f('ix_marketplace_contragent_cart_id'), 'marketplace_contragent_cart', ['id'], unique=False)
    op.create_table('marketplace_cart_goods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['marketplace_contragent_cart.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomenclature_id', 'warehouse_id', 'cart_id', name='ux_marketplace_cart_goods_nomenclature_id_warehouse_id_cart_id')
    )
    op.create_index(op.f('ix_marketplace_cart_goods_id'), 'marketplace_cart_goods', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_cart_goods_id'), table_name='marketplace_cart_goods')
    op.drop_table('marketplace_cart_goods')
    op.drop_index(op.f('ix_marketplace_contragent_cart_id'), table_name='marketplace_contragent_cart')
    op.drop_table('marketplace_contragent_cart')
    # ### end Alembic commands ###
