"""empty message

Revision ID: a2eed5d94a9e
Revises: a058bb8d62d6
Create Date: 2025-02-04 13:31:22.042769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2eed5d94a9e'
down_revision = 'a058bb8d62d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_triggers_events', sa.Column('before_event', sa.Boolean(), nullable=True))
    op.add_column('table_triggers_events', sa.Column('after_event', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_table_triggers_events_loyality_transactions_id'), 'table_triggers_events', ['loyality_transactions_id'], unique=False)
    op.create_index(op.f('ix_table_triggers_events_table_triggers_id'), 'table_triggers_events', ['table_triggers_id'], unique=False)
    op.create_unique_constraint(None, 'table_triggers_events', ['table_triggers_id', 'loyality_transactions_id'])
    op.drop_constraint('table_triggers_events_loyality_transactions_id_fkey', 'table_triggers_events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('table_triggers_events_loyality_transactions_id_fkey', 'table_triggers_events', 'loyality_transactions', ['loyality_transactions_id'], ['id'])
    op.drop_constraint(None, 'table_triggers_events', type_='unique')
    op.drop_index(op.f('ix_table_triggers_events_table_triggers_id'), table_name='table_triggers_events')
    op.drop_index(op.f('ix_table_triggers_events_loyality_transactions_id'), table_name='table_triggers_events')
    op.drop_column('table_triggers_events', 'after_event')
    op.drop_column('table_triggers_events', 'before_event')
    # ### end Alembic commands ###
