"""delivery

Revision ID: a50fca5eb33e
Revises: a0bba82afb52
Create Date: 2025-06-03 22:30:43.352201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50fca5eb33e'
down_revision = 'a0bba82afb52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs_sales_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docs_sales_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('general', 'picker', 'courier', name='role'), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['docs_sales_id'], ['docs_sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docs_sales_id', 'role', name='uix_docs_sales_links_docs_sales_id_role')
    )
    
    op.execute("CREATE TYPE orderstatus AS ENUM ('received', 'processed', 'collecting', 'collected', 'picked', 'delivered')")
    
    op.add_column('docs_sales', sa.Column('order_status', sa.Enum('received', 'processed', 'collecting', 'collected', 'picked', 'delivered', name='orderstatus', create_type=False), server_default='received', nullable=True))
    op.add_column('docs_sales', sa.Column('assigned_picker', sa.Integer(), nullable=True))
    op.add_column('docs_sales', sa.Column('picker_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('docs_sales', sa.Column('picker_finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('docs_sales', sa.Column('assigned_courier', sa.Integer(), nullable=True))
    op.add_column('docs_sales', sa.Column('courier_picked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('docs_sales', sa.Column('courier_delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'docs_sales', 'relation_tg_cashboxes', ['assigned_picker'], ['id'])
    op.create_foreign_key(None, 'docs_sales', 'relation_tg_cashboxes', ['assigned_courier'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("docs_sales_assigned_picker_fkey", 'docs_sales', type_='foreignkey')
    op.drop_constraint("docs_sales_assigned_courier_fkey", 'docs_sales', type_='foreignkey')
    op.drop_column('docs_sales', 'courier_delivered_at')
    op.drop_column('docs_sales', 'courier_picked_at')
    op.drop_column('docs_sales', 'assigned_courier')
    op.drop_column('docs_sales', 'picker_finished_at')
    op.drop_column('docs_sales', 'picker_started_at')
    op.drop_column('docs_sales', 'assigned_picker')
    op.drop_column('docs_sales', 'order_status')
    op.drop_table('docs_sales_links')
    op.execute("DROP TYPE orderstatus")
    # ### end Alembic commands ###
