"""location warehouse

Revision ID: a5f90f1d17da
Revises: 1c68f42fc047
Create Date: 2025-08-26 08:14:40.401481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f90f1d17da'
down_revision = '8e456631deb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('warehouses', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'longitude')
    op.drop_column('warehouses', 'latitude')
    # ### end Alembic commands ###
