"""create_channels_chats_tables

Revision ID: ac2ecd128db4
Revises: 32cf29284da2
Create Date: 2025-11-11 21:09:01.933204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac2ecd128db4'
down_revision = '32cf29284da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('AVITO', 'WHATSAPP', 'TELEGRAM', name='channeltype'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('svg_icon', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('api_config_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('contragent_id', sa.Integer(), nullable=True),
    sa.Column('cashbox_id', sa.Integer(), nullable=False),
    sa.Column('external_chat_id', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'ARCHIVED', name='chatstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('assigned_operator_id', sa.Integer(), nullable=True),
    sa.Column('first_message_time', sa.DateTime(), nullable=True),
    sa.Column('first_response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('last_message_time', sa.DateTime(), nullable=True),
    sa.Column('last_response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_operator_id'], ['relation_tg_cashboxes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'external_chat_id', 'cashbox_id', name='uq_chats_channel_external_cashbox')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('CLIENT', 'OPERATOR', name='messagesendertype'), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'DOCUMENT', 'VOICE', 'SYSTEM', name='messagetype'), server_default='TEXT', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus'), server_default='SENT', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем таблицы в обратном порядке (сначала зависимые)
    op.drop_table('chat_messages')
    op.drop_table('chats')
    op.drop_table('channels')
    
    # Удаляем enum типы
    op.execute('DROP TYPE IF EXISTS messagestatus')
    op.execute('DROP TYPE IF EXISTS messagetype')
    op.execute('DROP TYPE IF EXISTS messagesendertype')
    op.execute('DROP TYPE IF EXISTS chatstatus')
    op.execute('DROP TYPE IF EXISTS channeltype')
    # ### end Alembic commands ###
