"""Added new price_type - work

Revision ID: ace9991191d4
Revises: 49e948206f88
Create Date: 2025-11-27 16:31:28.626477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace9991191d4'
down_revision = '49e948206f88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_types', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_types', 'tags')
    # ### end Alembic commands ###
