"""add marketplace

Revision ID: af297d88e7fa
Revises: 5633b0a50e72
Create Date: 2025-11-11 07:39:39.146407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af297d88e7fa'
down_revision = '5633b0a50e72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_rating_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_rating_aggregates_id'), 'marketplace_rating_aggregates', ['id'], unique=False)
    op.create_table('marketplace_utm_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_medium', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('utm_term', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('utm_content', sa.String(), nullable=True),
    sa.Column('utm_name', sa.String(), nullable=True),
    sa.Column('utm_phone', sa.String(), nullable=True),
    sa.Column('utm_email', sa.String(), nullable=True),
    sa.Column('utm_leadid', sa.String(), nullable=True),
    sa.Column('utm_yclientid', sa.String(), nullable=True),
    sa.Column('utm_gaclientid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_utm_tags_id'), 'marketplace_utm_tags', ['id'], unique=False)
    op.create_table('marketplace_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('contagent_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='visible', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contagent_id'], ['contragents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_reviews_id'), 'marketplace_reviews', ['id'], unique=False)
    op.create_table('marketplace_view_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('listing_pos', sa.Integer(), nullable=True),
    sa.Column('listing_page', sa.Integer(), nullable=True),
    sa.Column('contragent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_view_events_id'), 'marketplace_view_events', ['id'], unique=False)
    op.create_table('favorites_nomenclatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('contagent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contagent_id'], ['contragents.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_nomenclatures_id'), 'favorites_nomenclatures', ['id'], unique=False)

    op.add_column('docs_sales', sa.Column('is_marketplace_order', sa.Boolean(), server_default='false', nullable=True))

    op.add_column('warehouses', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # Удаление новых таблиц (в обратном порядке создания)
    op.drop_index(op.f('ix_favorites_nomenclatures_id'), table_name='favorites_nomenclatures')
    op.drop_table('favorites_nomenclatures')

    op.drop_index(op.f('ix_marketplace_view_events_id'), table_name='marketplace_view_events')
    op.drop_table('marketplace_view_events')

    op.drop_index(op.f('ix_marketplace_reviews_id'), table_name='marketplace_reviews')
    op.drop_table('marketplace_reviews')

    op.drop_index(op.f('ix_marketplace_utm_tags_id'), table_name='marketplace_utm_tags')
    op.drop_table('marketplace_utm_tags')

    op.drop_index(op.f('ix_marketplace_rating_aggregates_id'), table_name='marketplace_rating_aggregates')
    op.drop_table('marketplace_rating_aggregates')

    # Удаление добавленных столбцов
    op.drop_column('warehouses', 'is_public')
    op.drop_column('docs_sales', 'is_marketplace_order')

    # Удаление внешних ключей (они были добавлены без имени — Alembic генерирует автоматические имена)
    # Чтобы точно удалить, нужно указать имя ограничения или использовать None + type_='foreignkey'
    # В upgrade они добавлялись без явного имени, поэтому в downgrade удаляем так же:
    op.drop_constraint(None, 'tech_operation_components', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
