"""empty message

Revision ID: aff3ea629e6a
Revises: bdf5951a422a
Create Date: 2024-12-16 11:48:39.927976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff3ea629e6a'
down_revision = 'bdf5951a422a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_amo_bots_ext_id'), 'amo_bots', ['ext_id'], unique=False)
    op.create_index(op.f('ix_amo_bots_install_group_id'), 'amo_bots', ['install_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amo_bots_install_group_id'), table_name='amo_bots')
    op.drop_index(op.f('ix_amo_bots_ext_id'), table_name='amo_bots')
    # ### end Alembic commands ###
