"""add/fields_to_segment_model

Revision ID: b434531c9ee3
Revises: 228aca7114ac
Create Date: 2025-06-02 21:21:07.663490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b434531c9ee3'
down_revision = '228aca7114ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('uuid', postgresql.UUID(), nullable=False))
    op.add_column('segments', sa.Column('type_of_update', sa.String(), nullable=False))
    op.add_column('segments', sa.Column('update_settings', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_segments_uuid'), 'segments', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_uuid'), table_name='segments')
    op.drop_column('segments', 'update_settings')
    op.drop_column('segments', 'type_of_update')
    op.drop_column('segments', 'uuid')
    # ### end Alembic commands ###
