"""Add type cashback nomenclature

Revision ID: b8cb133ee445
Revises: 1366a50d9d76
Create Date: 2025-04-16 02:35:47.111853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8cb133ee445'
down_revision = '1366a50d9d76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    nomenclature_cashback_enum = sa.Enum(
        'percent', 'const', 'no_cashback', 'lcard_cashback',
        name='nomenclaturecashbacktype'
    )
    nomenclature_cashback_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('nomenclature', sa.Column('cashback_type', nomenclature_cashback_enum, nullable=False, server_default="no_cashback"))
    op.alter_column('nomenclature', 'cashback_percent', new_column_name='cashback_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nomenclature', 'cashback_value', new_column_name='cashback_percent')
    op.drop_column('nomenclature', 'cashback_type')
    op.execute('DROP TYPE IF EXISTS nomenclaturecashbacktype')
    # ### end Alembic commands ###
