"""add_table_booking_tags

Revision ID: b8dc83d31996
Revises: 43e4a2d80a61
Create Date: 2024-10-20 14:33:57.225728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8dc83d31996'
down_revision = '43e4a2d80a61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookikng.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_tags_id'), 'booking_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_tags_id'), table_name='booking_tags')
    op.drop_table('booking_tags')
    # ### end Alembic commands ###
