"""add apple wallet table

Revision ID: b93707ca0d3d
Revises: optimize_segments_003
Create Date: 2025-10-18 07:34:08.212350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93707ca0d3d'
down_revision = 'optimize_segments_003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apple_push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_library_identifier', sa.String(), nullable=False),
    sa.Column('pass_type_id', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('push_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apple_push_tokens')
    # ### end Alembic commands ###
