"""Add format phone

Revision ID: bb8796c37a4c
Revises: 9cbed7e801c5
Create Date: 2025-02-26 01:48:06.602193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8796c37a4c'
down_revision = '9cbed7e801c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amo_contacts', sa.Column('phone_code', sa.String(), nullable=True))
    op.add_column('contragents', sa.Column('phone_code', sa.String(), nullable=True))
    op.add_column('contragents', sa.Column('is_phone_formatted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contragents', 'is_phone_formatted')
    op.drop_column('contragents', 'phone_code')
    op.drop_column('amo_contacts', 'phone_code')
    # ### end Alembic commands ###
