"""add have_updated_field

Revision ID: bd1abe3b8137
Revises: 0037f781239f
Create Date: 2025-10-18 11:38:35.398785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1abe3b8137'
down_revision = '33de7c3df2b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apple_push_tokens', sa.Column('have_updates', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apple_push_tokens', 'have_updates')
    # ### end Alembic commands ###
