"""empty message

Revision ID: bdf5951a422a
Revises: 282fa3cb3e98
Create Date: 2024-12-16 11:47:22.003231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf5951a422a'
down_revision = '282fa3cb3e98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('amo_bots_ext_id_key', 'amo_bots', type_='unique')
    op.drop_constraint('amo_bots_install_group_id_key', 'amo_bots', type_='unique')
    op.create_unique_constraint(None, 'amo_bots', ['install_group_id', 'ext_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'amo_bots', type_='unique')
    op.create_unique_constraint('amo_bots_install_group_id_key', 'amo_bots', ['install_group_id'])
    op.create_unique_constraint('amo_bots_ext_id_key', 'amo_bots', ['ext_id'])
    # ### end Alembic commands ###
