"""Add unique key

Revision ID: c8b044f53221
Revises: bb8796c37a4c
Create Date: 2025-02-26 04:59:04.840196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b044f53221'
down_revision = 'bb8796c37a4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_amo_install_groups_referrer", 'amo_install_groups', ['referrer'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_amo_install_groups_referrer", 'amo_install_groups', type_='unique')
    # ### end Alembic commands ###
