"""add_utm_tags

Revision ID: c900ea9bbaf9
Revises: 854e54846d57
Create Date: 2025-03-21 21:37:16.103236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c900ea9bbaf9'
down_revision = '74b7d63c1eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs_sales_delivery_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docs_sales_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['docs_sales_id'], ['docs_sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_sales_delivery_info_id'), 'docs_sales_delivery_info', ['id'], unique=False)
    op.create_table('docs_sales_utm_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('docs_sales_id', sa.Integer(), nullable=True),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_medium', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('utm_term', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('utm_content', sa.String(), nullable=True),
    sa.Column('utm_name', sa.String(), nullable=True),
    sa.Column('utm_phone', sa.String(), nullable=True),
    sa.Column('utm_email', sa.String(), nullable=True),
    sa.Column('utm_leadid', sa.String(), nullable=True),
    sa.Column('utm_yclientid', sa.String(), nullable=True),
    sa.Column('utm_gaclientid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['docs_sales_id'], ['docs_sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_sales_utm_tags_id'), 'docs_sales_utm_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docs_sales_utm_tags_id'), table_name='docs_sales_utm_tags')
    op.drop_table('docs_sales_utm_tags')
    op.drop_index(op.f('ix_docs_sales_delivery_info_id'), table_name='docs_sales_delivery_info')
    op.drop_table('docs_sales_delivery_info')
    # ### end Alembic commands ###
