"""Remove Foreign key

Revision ID: d14f8e267dc1
Revises: c8b044f53221
Create Date: 2025-02-26 05:29:44.453747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14f8e267dc1'
down_revision = 'c8b044f53221'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('amo_lead_statuses_pipeline_id_fkey', 'amo_lead_statuses', type_='foreignkey')
    op.drop_constraint('amo_leads_status_id_fkey', 'amo_leads', type_='foreignkey')
    op.drop_constraint('amo_leads_pipeline_id_fkey', 'amo_leads', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('amo_leads_pipeline_id_fkey', 'amo_leads', 'amo_lead_pipelines', ['pipeline_id'], ['id'])
    op.create_foreign_key('amo_leads_status_id_fkey', 'amo_leads', 'amo_lead_statuses', ['status_id'], ['id'])
    op.create_foreign_key('amo_lead_statuses_pipeline_id_fkey', 'amo_lead_statuses', 'amo_lead_pipelines', ['pipeline_id'], ['id'])
    # ### end Alembic commands ###
