"""add amo_docs_sales_delivery_contragents

Revision ID: d4c89dd4b537
Revises: a0bba82afb52
Create Date: 2025-06-15 15:19:00.744155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c89dd4b537'
down_revision = 'a50fca5eb33e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_docs_sales_delivery_contragents',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('delivery_info_id', sa.Integer(), nullable=False),
        sa.Column('contragent_id', sa.Integer(), nullable=False),
        sa.Column('amo_install_group_id', sa.Integer(), nullable=True),
        sa.Column('cashbox_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['amo_install_group_id'], ['amo_install_groups.id'], ),
        sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
        sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], ),
        sa.ForeignKeyConstraint(['delivery_info_id'], ['docs_sales_delivery_info.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amo_docs_sales_delivery_contragents_id'), 'amo_docs_sales_delivery_contragents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amo_docs_sales_delivery_contragents_id'), table_name='amo_docs_sales_delivery_contragents')
    op.drop_table('amo_docs_sales_delivery_contragents')
    # ### end Alembic commands ###
