"""empty message

Revision ID: d901b6589a30
Revises: 15f51b4bd1da, 8eb1872d5402
Create Date: 2024-11-27 09:04:35.269367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd901b6589a30'
down_revision = '8eb1872d5402'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type_functionality', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('amo_bot_handler_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amo_bots_id'), 'amo_bots', ['id'], unique=False)
    op.create_table('table_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=True),
    sa.Column('amo_bots_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['amo_bots_id'], ['amo_bots.id'], ),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_triggers_id'), 'table_triggers', ['id'], unique=False)
    op.create_table('table_triggers_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=True),
    sa.Column('table_triggers_id', sa.Integer(), nullable=True),
    sa.Column('client', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.ForeignKeyConstraint(['table_triggers_id'], ['table_triggers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_triggers_events_id'), 'table_triggers_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_triggers_events_id'), table_name='table_triggers_events')
    op.drop_table('table_triggers_events')
    op.drop_index(op.f('ix_table_triggers_id'), table_name='table_triggers')
    op.drop_table('table_triggers')
    op.drop_index(op.f('ix_amo_bots_id'), table_name='amo_bots')
    op.drop_table('amo_bots')
    # ### end Alembic commands ###
