"""Add field docs_sales_id to tbank_orders

Revision ID: dbbe06a4083d
Revises: b8dc83d31996
Create Date: 2024-11-04 11:58:22.534423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbe06a4083d'
down_revision = 'b8dc83d31996'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbank_orders', sa.Column('docs_sales_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbank_orders', 'docs_sales', ['docs_sales_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbank_orders', type_='foreignkey')
    op.drop_column('tbank_orders', 'docs_sales_id')
    # ### end Alembic commands ###
