"""Add Unique Index

Revision ID: e051f8236e22
Revises: 6eacf82668e4
Create Date: 2025-01-26 12:37:52.960635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e051f8236e22'
down_revision = '6eacf82668e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_table_id_main', 'amo_table_contacts', ['table_id'], unique=True, postgresql_where=sa.text('is_main = true'))
    op.create_unique_constraint(None, 'amo_table_contacts', ['amo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'amo_table_contacts', type_='unique')
    op.drop_index('uq_table_id_main', table_name='amo_table_contacts', postgresql_where=sa.text('is_main = true'))
    # ### end Alembic commands ###
