"""empty message

Revision ID: e090f4caa808
Revises: 7f4466d297af
Create Date: 2024-12-16 11:39:47.994943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e090f4caa808'
down_revision = '7f4466d297af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_bots_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('silent', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_working_without_chat', sa.Boolean(), nullable=True),
    sa.Column('type_functionality', sa.Integer(), nullable=True),
    sa.Column('amo_bots_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['amo_bots_id'], ['amo_bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amo_bots_settings_id'), 'amo_bots_settings', ['id'], unique=False)
    op.add_column('amo_bots', sa.Column('ext_id', sa.Integer(), nullable=True))
    op.add_column('amo_bots', sa.Column('install_group_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'amo_bots', ['ext_id'])
    op.drop_constraint('amo_bots_cashbox_id_fkey', 'amo_bots', type_='foreignkey')
    op.create_foreign_key(None, 'amo_bots', 'amo_install_groups', ['install_group_id'], ['id'])
    op.drop_column('amo_bots', 'cashbox_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amo_bots', sa.Column('cashbox_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'amo_bots', type_='foreignkey')
    op.create_foreign_key('amo_bots_cashbox_id_fkey', 'amo_bots', 'cashboxes', ['cashbox_id'], ['id'])
    op.drop_constraint(None, 'amo_bots', type_='unique')
    op.drop_column('amo_bots', 'install_group_id')
    op.drop_column('amo_bots', 'ext_id')
    op.drop_index(op.f('ix_amo_bots_settings_id'), table_name='amo_bots_settings')
    op.drop_table('amo_bots_settings')
    # ### end Alembic commands ###
