"""add_field_to_amo_table_contacts

Revision ID: e55ec8843476
Revises: 51a676700853
Create Date: 2024-10-16 08:58:31.954926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55ec8843476'
down_revision = '51a676700853'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amo_table_contacts', sa.Column('is_main', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amo_table_contacts', 'is_main')
    # ### end Alembic commands ###
