"""contragent_tag_link

Revision ID: f7df2c79bff0
Revises: 1a5a3f7507cd
Create Date: 2025-07-07 17:29:51.576095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7df2c79bff0'
down_revision = '1a5a3f7507cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contragents_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('contragent_id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], ),
    sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'contragent_id', name='unique_tag_id_contragent_id')
    )
    op.create_index(op.f('ix_contragents_tags_id'), 'contragents_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contragents_tags_id'), table_name='contragents_tags')
    op.drop_table('contragents_tags')
    # ### end Alembic commands ###
