"""fix/segment_model_is_archive_field

Revision ID: f82fc5198d96
Revises: 5bfab8513113
Create Date: 2025-06-09 22:45:07.140947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f82fc5198d96'
down_revision = '5bfab8513113'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'is_archived')
    # ### end Alembic commands ###
