"""Add custom fields

Revision ID: fab805a9d974
Revises: dbbe06a4083d
Create Date: 2024-11-06 23:08:09.626381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab805a9d974'
down_revision = 'dbbe06a4083d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_custom_fields',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type_entity', sa.Enum('Contact', 'Lead', name='typecustomfield'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amo_custom_fields_id'), 'amo_custom_fields', ['id'], unique=False)
    op.create_table('amo_install_custom_fields',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['custom_field_id'], ['amo_custom_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'cashbox_id')
    )
    op.create_index(op.f('ix_amo_install_custom_fields_id'), 'amo_install_custom_fields', ['id'], unique=False)
    op.create_table('amo_entity_custom_fields',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['amo_contacts.id'], ),
    sa.ForeignKeyConstraint(['custom_field_id'], ['amo_custom_fields.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['amo_leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'lead_id', 'contact_id')
    )
    op.create_index(op.f('ix_amo_entity_custom_fields_contact_id'), 'amo_entity_custom_fields', ['contact_id'], unique=False)
    op.create_index(op.f('ix_amo_entity_custom_fields_id'), 'amo_entity_custom_fields', ['id'], unique=False)
    op.create_index(op.f('ix_amo_entity_custom_fields_lead_id'), 'amo_entity_custom_fields', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amo_entity_custom_fields_lead_id'), table_name='amo_entity_custom_fields')
    op.drop_index(op.f('ix_amo_entity_custom_fields_id'), table_name='amo_entity_custom_fields')
    op.drop_index(op.f('ix_amo_entity_custom_fields_contact_id'), table_name='amo_entity_custom_fields')
    op.drop_table('amo_entity_custom_fields')
    op.drop_index(op.f('ix_amo_install_custom_fields_id'), table_name='amo_install_custom_fields')
    op.drop_table('amo_install_custom_fields')
    op.drop_index(op.f('ix_amo_custom_fields_id'), table_name='amo_custom_fields')
    op.drop_table('amo_custom_fields')
    # ### end Alembic commands ###
