from api.docs_sales.application.queries.GetDocsSalesListQuery import GetDocsSalesListQuery
from api.docs_sales.application.queries.GetDocsSalesListByCreatedDateQuery import GetDocsSalesListByCreatedDateQuery
from api.docs_sales.application.queries.GetDocsSalesListByDeliveryDateQuery import GetDocsSalesListByDeliveryDateQuery
from api.docs_sales.application.queries.GetDocSaleByIdQuery import GetDocSaleByIdQuery