from apps.amocrm.installer.infrastructure.models.PatchWidgetInstallerInfoModel import PatchWidgetInstallerInfoModel


class ResponsePatchWidgetInstallerInfoModel(PatchWidgetInstallerInfoModel):
    pass